# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
  paths:
    include: # Include!
      - 'Client/*' # or 'service-b/*'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.16.0'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@12.0.5
    npm install
    ng build --prod
  displayName: 'npm install and build'
  workingDirectory: Client
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Client/dist/Client'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'