# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
  paths:
    include: # Include!
      - 'Client/*' # or 'service-b/*'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.13.0'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@15.2.11
    npm install
    ng build --prod
  displayName: 'npm install and build'
  workingDirectory: Client

- task: replacetokens@5
  inputs:
    targetFiles: 'Client/dist/**/main*.js'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'fail'
    keepToken: false
    actionOnNoFiles: 'fail'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- task: CopyPublishBuildArtifacts@1
  displayName: 'Copy Publish Artifact: angular-web-app'
  inputs:
    CopyRoot: Client/dist
    Contents: '**'
    ArtifactName: angular-web-app
    ArtifactType: Container